services:
  db:
    image: mysql:8
    container_name: powergym_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: powergym_app
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - powergym_network

  app:
    image: powergym-app
    container_name: powergym_app
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: powergym_app
    volumes:
      - ./Backend/uploads:/app/Backend/uploads
    networks:
      - powergym_network

  nginx:
    image: nginx:latest
    container_name: powergym_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - powergym_network

volumes:
  db_data:

networks:
  powergym_network:
    driver: bridge
