version: '3.8'

services:
  app:
    build: .
    container_name: powergym_app
    ports:
      - "80:3000"
    volumes:
      - ./Backend/uploads:/app/Backend/uploads
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: powergym_app
    restart: always

  db:
    image: mysql:8
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: powergym_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: powergym_app
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data: